/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose } from "class-transformer";

/**
 * Internal Server Error
 */
export class CreatePhoneNumberResponse500ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneNumberResponse500ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneNumberResponse500ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneNumberResponse500ResponseBody.prototype);
    }
}

/**
 * Unprocessable Content
 */
export class CreatePhoneNumberResponse422ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneNumberResponse422ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneNumberResponse422ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneNumberResponse422ResponseBody.prototype);
    }
}

/**
 * Payment Required
 */
export class CreatePhoneNumberResponse402ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneNumberResponse402ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneNumberResponse402ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneNumberResponse402ResponseBody.prototype);
    }
}

/**
 * Unauthorized
 */
export class CreatePhoneNumberResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneNumberResponseResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneNumberResponseResponseBody";
        Object.setPrototypeOf(this, CreatePhoneNumberResponseResponseBody.prototype);
    }
}

/**
 * Bad Request
 */
export class CreatePhoneNumberResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneNumberResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneNumberResponseBody";
        Object.setPrototypeOf(this, CreatePhoneNumberResponseBody.prototype);
    }
}
