/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose } from "class-transformer";

/**
 * Internal Server Error
 */
export class CreatePhoneCallResponse500ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneCallResponse500ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneCallResponse500ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneCallResponse500ResponseBody.prototype);
    }
}

/**
 * Too Many Requests
 */
export class CreatePhoneCallResponse429ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneCallResponse429ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneCallResponse429ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneCallResponse429ResponseBody.prototype);
    }
}

/**
 * Unprocessable Content
 */
export class CreatePhoneCallResponse422ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneCallResponse422ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneCallResponse422ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneCallResponse422ResponseBody.prototype);
    }
}

/**
 * Payment Required
 */
export class CreatePhoneCallResponse402ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneCallResponse402ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneCallResponse402ResponseBody";
        Object.setPrototypeOf(this, CreatePhoneCallResponse402ResponseBody.prototype);
    }
}

/**
 * Unauthorized
 */
export class CreatePhoneCallResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneCallResponseResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneCallResponseResponseBody";
        Object.setPrototypeOf(this, CreatePhoneCallResponseResponseBody.prototype);
    }
}

/**
 * Bad Request
 */
export class CreatePhoneCallResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: CreatePhoneCallResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "CreatePhoneCallResponseBody";
        Object.setPrototypeOf(this, CreatePhoneCallResponseBody.prototype);
    }
}
