/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose } from "class-transformer";

/**
 * Internal Server Error
 */
export class ListPhoneNumbersResponse500ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: ListPhoneNumbersResponse500ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ListPhoneNumbersResponse500ResponseBody";
        Object.setPrototypeOf(this, ListPhoneNumbersResponse500ResponseBody.prototype);
    }
}

/**
 * Unauthorized
 */
export class ListPhoneNumbersResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: ListPhoneNumbersResponseResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ListPhoneNumbersResponseResponseBody";
        Object.setPrototypeOf(this, ListPhoneNumbersResponseResponseBody.prototype);
    }
}

/**
 * Bad Request
 */
export class ListPhoneNumbersResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: ListPhoneNumbersResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ListPhoneNumbersResponseBody";
        Object.setPrototypeOf(this, ListPhoneNumbersResponseBody.prototype);
    }
}
