/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * Internal Server Error
 */
export type RegisterCallResponse500ResponseBodyData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;
};

/**
 * Internal Server Error
 */
export class RegisterCallResponse500ResponseBody extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RegisterCallResponse500ResponseBodyData;

  constructor(
    err: RegisterCallResponse500ResponseBodyData,
    options?: ErrorOptions,
  ) {
    super("", options);
    this.data$ = err;

    if (err.rawResponse != null) {
      this.rawResponse = err.rawResponse;
    }
    if (err.errorMessage != null) {
      this.errorMessage = err.errorMessage;
    }

    const msg =
      "message" in err && typeof err.message === "string" ? err.message : "";
    const { rawResponse, ...data } = err;
    const content = JSON.stringify(data);
    this.message = [msg, content].filter(Boolean).join("\n");

    this.name = "RegisterCallResponse500ResponseBody";
  }
}

/**
 * Too Many Requests
 */
export type RegisterCallResponse429ResponseBodyData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;
};

/**
 * Too Many Requests
 */
export class RegisterCallResponse429ResponseBody extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RegisterCallResponse429ResponseBodyData;

  constructor(
    err: RegisterCallResponse429ResponseBodyData,
    options?: ErrorOptions,
  ) {
    super("", options);
    this.data$ = err;

    if (err.rawResponse != null) {
      this.rawResponse = err.rawResponse;
    }
    if (err.errorMessage != null) {
      this.errorMessage = err.errorMessage;
    }

    const msg =
      "message" in err && typeof err.message === "string" ? err.message : "";
    const { rawResponse, ...data } = err;
    const content = JSON.stringify(data);
    this.message = [msg, content].filter(Boolean).join("\n");

    this.name = "RegisterCallResponse429ResponseBody";
  }
}

/**
 * Unprocessable Content
 */
export type RegisterCallResponse422ResponseBodyData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;
};

/**
 * Unprocessable Content
 */
export class RegisterCallResponse422ResponseBody extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RegisterCallResponse422ResponseBodyData;

  constructor(
    err: RegisterCallResponse422ResponseBodyData,
    options?: ErrorOptions,
  ) {
    super("", options);
    this.data$ = err;

    if (err.rawResponse != null) {
      this.rawResponse = err.rawResponse;
    }
    if (err.errorMessage != null) {
      this.errorMessage = err.errorMessage;
    }

    const msg =
      "message" in err && typeof err.message === "string" ? err.message : "";
    const { rawResponse, ...data } = err;
    const content = JSON.stringify(data);
    this.message = [msg, content].filter(Boolean).join("\n");

    this.name = "RegisterCallResponse422ResponseBody";
  }
}

/**
 * Payment Required
 */
export type RegisterCallResponse402ResponseBodyData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;
};

/**
 * Payment Required
 */
export class RegisterCallResponse402ResponseBody extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RegisterCallResponse402ResponseBodyData;

  constructor(
    err: RegisterCallResponse402ResponseBodyData,
    options?: ErrorOptions,
  ) {
    super("", options);
    this.data$ = err;

    if (err.rawResponse != null) {
      this.rawResponse = err.rawResponse;
    }
    if (err.errorMessage != null) {
      this.errorMessage = err.errorMessage;
    }

    const msg =
      "message" in err && typeof err.message === "string" ? err.message : "";
    const { rawResponse, ...data } = err;
    const content = JSON.stringify(data);
    this.message = [msg, content].filter(Boolean).join("\n");

    this.name = "RegisterCallResponse402ResponseBody";
  }
}

/**
 * Unauthorized
 */
export type RegisterCallResponseResponseBodyData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;
};

/**
 * Unauthorized
 */
export class RegisterCallResponseResponseBody extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RegisterCallResponseResponseBodyData;

  constructor(
    err: RegisterCallResponseResponseBodyData,
    options?: ErrorOptions,
  ) {
    super("", options);
    this.data$ = err;

    if (err.rawResponse != null) {
      this.rawResponse = err.rawResponse;
    }
    if (err.errorMessage != null) {
      this.errorMessage = err.errorMessage;
    }

    const msg =
      "message" in err && typeof err.message === "string" ? err.message : "";
    const { rawResponse, ...data } = err;
    const content = JSON.stringify(data);
    this.message = [msg, content].filter(Boolean).join("\n");

    this.name = "RegisterCallResponseResponseBody";
  }
}

/**
 * Bad Request
 */
export type RegisterCallResponseBodyData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;
};

/**
 * Bad Request
 */
export class RegisterCallResponseBody extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  errorMessage?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: RegisterCallResponseBodyData;

  constructor(err: RegisterCallResponseBodyData, options?: ErrorOptions) {
    super("", options);
    this.data$ = err;

    if (err.rawResponse != null) {
      this.rawResponse = err.rawResponse;
    }
    if (err.errorMessage != null) {
      this.errorMessage = err.errorMessage;
    }

    const msg =
      "message" in err && typeof err.message === "string" ? err.message : "";
    const { rawResponse, ...data } = err;
    const content = JSON.stringify(data);
    this.message = [msg, content].filter(Boolean).join("\n");

    this.name = "RegisterCallResponseBody";
  }
}

/** @internal */
export namespace RegisterCallResponse500ResponseBody$ {
  export type Inbound = {
    RawResponse?: Response | undefined;
    error_message?: string | undefined;
  };

  export const inboundSchema: z.ZodType<
    RegisterCallResponse500ResponseBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RawResponse: z.instanceof(Response).optional(),
      error_message: z.string().optional(),
    })
    .transform((v) => {
      return new RegisterCallResponse500ResponseBody({
        ...(v.RawResponse === undefined
          ? null
          : { rawResponse: v.RawResponse }),
        ...(v.error_message === undefined
          ? null
          : { errorMessage: v.error_message }),
      });
    });
  export type Outbound = {
    RawResponse?: never | undefined;
    error_message?: string | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    RegisterCallResponse500ResponseBody
  > = z
    .instanceof(RegisterCallResponse500ResponseBody)
    .transform((v) => v.data$)
    .pipe(
      z
        .object({
          rawResponse: z
            .instanceof(Response)
            .transform(() => {
              throw new Error("Response cannot be serialized");
            })
            .optional(),
          errorMessage: z.string().optional(),
        })
        .transform((v) => {
          return {
            ...(v.rawResponse === undefined
              ? null
              : { RawResponse: v.rawResponse }),
            ...(v.errorMessage === undefined
              ? null
              : { error_message: v.errorMessage }),
          };
        }),
    );
}

/** @internal */
export namespace RegisterCallResponse429ResponseBody$ {
  export type Inbound = {
    RawResponse?: Response | undefined;
    error_message?: string | undefined;
  };

  export const inboundSchema: z.ZodType<
    RegisterCallResponse429ResponseBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RawResponse: z.instanceof(Response).optional(),
      error_message: z.string().optional(),
    })
    .transform((v) => {
      return new RegisterCallResponse429ResponseBody({
        ...(v.RawResponse === undefined
          ? null
          : { rawResponse: v.RawResponse }),
        ...(v.error_message === undefined
          ? null
          : { errorMessage: v.error_message }),
      });
    });
  export type Outbound = {
    RawResponse?: never | undefined;
    error_message?: string | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    RegisterCallResponse429ResponseBody
  > = z
    .instanceof(RegisterCallResponse429ResponseBody)
    .transform((v) => v.data$)
    .pipe(
      z
        .object({
          rawResponse: z
            .instanceof(Response)
            .transform(() => {
              throw new Error("Response cannot be serialized");
            })
            .optional(),
          errorMessage: z.string().optional(),
        })
        .transform((v) => {
          return {
            ...(v.rawResponse === undefined
              ? null
              : { RawResponse: v.rawResponse }),
            ...(v.errorMessage === undefined
              ? null
              : { error_message: v.errorMessage }),
          };
        }),
    );
}

/** @internal */
export namespace RegisterCallResponse422ResponseBody$ {
  export type Inbound = {
    RawResponse?: Response | undefined;
    error_message?: string | undefined;
  };

  export const inboundSchema: z.ZodType<
    RegisterCallResponse422ResponseBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RawResponse: z.instanceof(Response).optional(),
      error_message: z.string().optional(),
    })
    .transform((v) => {
      return new RegisterCallResponse422ResponseBody({
        ...(v.RawResponse === undefined
          ? null
          : { rawResponse: v.RawResponse }),
        ...(v.error_message === undefined
          ? null
          : { errorMessage: v.error_message }),
      });
    });
  export type Outbound = {
    RawResponse?: never | undefined;
    error_message?: string | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    RegisterCallResponse422ResponseBody
  > = z
    .instanceof(RegisterCallResponse422ResponseBody)
    .transform((v) => v.data$)
    .pipe(
      z
        .object({
          rawResponse: z
            .instanceof(Response)
            .transform(() => {
              throw new Error("Response cannot be serialized");
            })
            .optional(),
          errorMessage: z.string().optional(),
        })
        .transform((v) => {
          return {
            ...(v.rawResponse === undefined
              ? null
              : { RawResponse: v.rawResponse }),
            ...(v.errorMessage === undefined
              ? null
              : { error_message: v.errorMessage }),
          };
        }),
    );
}

/** @internal */
export namespace RegisterCallResponse402ResponseBody$ {
  export type Inbound = {
    RawResponse?: Response | undefined;
    error_message?: string | undefined;
  };

  export const inboundSchema: z.ZodType<
    RegisterCallResponse402ResponseBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RawResponse: z.instanceof(Response).optional(),
      error_message: z.string().optional(),
    })
    .transform((v) => {
      return new RegisterCallResponse402ResponseBody({
        ...(v.RawResponse === undefined
          ? null
          : { rawResponse: v.RawResponse }),
        ...(v.error_message === undefined
          ? null
          : { errorMessage: v.error_message }),
      });
    });
  export type Outbound = {
    RawResponse?: never | undefined;
    error_message?: string | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    RegisterCallResponse402ResponseBody
  > = z
    .instanceof(RegisterCallResponse402ResponseBody)
    .transform((v) => v.data$)
    .pipe(
      z
        .object({
          rawResponse: z
            .instanceof(Response)
            .transform(() => {
              throw new Error("Response cannot be serialized");
            })
            .optional(),
          errorMessage: z.string().optional(),
        })
        .transform((v) => {
          return {
            ...(v.rawResponse === undefined
              ? null
              : { RawResponse: v.rawResponse }),
            ...(v.errorMessage === undefined
              ? null
              : { error_message: v.errorMessage }),
          };
        }),
    );
}

/** @internal */
export namespace RegisterCallResponseResponseBody$ {
  export type Inbound = {
    RawResponse?: Response | undefined;
    error_message?: string | undefined;
  };

  export const inboundSchema: z.ZodType<
    RegisterCallResponseResponseBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RawResponse: z.instanceof(Response).optional(),
      error_message: z.string().optional(),
    })
    .transform((v) => {
      return new RegisterCallResponseResponseBody({
        ...(v.RawResponse === undefined
          ? null
          : { rawResponse: v.RawResponse }),
        ...(v.error_message === undefined
          ? null
          : { errorMessage: v.error_message }),
      });
    });
  export type Outbound = {
    RawResponse?: never | undefined;
    error_message?: string | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    RegisterCallResponseResponseBody
  > = z
    .instanceof(RegisterCallResponseResponseBody)
    .transform((v) => v.data$)
    .pipe(
      z
        .object({
          rawResponse: z
            .instanceof(Response)
            .transform(() => {
              throw new Error("Response cannot be serialized");
            })
            .optional(),
          errorMessage: z.string().optional(),
        })
        .transform((v) => {
          return {
            ...(v.rawResponse === undefined
              ? null
              : { RawResponse: v.rawResponse }),
            ...(v.errorMessage === undefined
              ? null
              : { error_message: v.errorMessage }),
          };
        }),
    );
}

/** @internal */
export namespace RegisterCallResponseBody$ {
  export type Inbound = {
    RawResponse?: Response | undefined;
    error_message?: string | undefined;
  };

  export const inboundSchema: z.ZodType<
    RegisterCallResponseBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RawResponse: z.instanceof(Response).optional(),
      error_message: z.string().optional(),
    })
    .transform((v) => {
      return new RegisterCallResponseBody({
        ...(v.RawResponse === undefined
          ? null
          : { rawResponse: v.RawResponse }),
        ...(v.error_message === undefined
          ? null
          : { errorMessage: v.error_message }),
      });
    });
  export type Outbound = {
    RawResponse?: never | undefined;
    error_message?: string | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    RegisterCallResponseBody
  > = z
    .instanceof(RegisterCallResponseBody)
    .transform((v) => v.data$)
    .pipe(
      z
        .object({
          rawResponse: z
            .instanceof(Response)
            .transform(() => {
              throw new Error("Response cannot be serialized");
            })
            .optional(),
          errorMessage: z.string().optional(),
        })
        .transform((v) => {
          return {
            ...(v.rawResponse === undefined
              ? null
              : { RawResponse: v.rawResponse }),
            ...(v.errorMessage === undefined
              ? null
              : { error_message: v.errorMessage }),
          };
        }),
    );
}
