/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose } from "class-transformer";

/**
 * Internal Server Error
 */
export class UpdateAgentResponse500ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: UpdateAgentResponse500ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "UpdateAgentResponse500ResponseBody";
        Object.setPrototypeOf(this, UpdateAgentResponse500ResponseBody.prototype);
    }
}

/**
 * Unprocessable Content
 */
export class UpdateAgentResponse422ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: UpdateAgentResponse422ResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "UpdateAgentResponse422ResponseBody";
        Object.setPrototypeOf(this, UpdateAgentResponse422ResponseBody.prototype);
    }
}

/**
 * Unauthorized
 */
export class UpdateAgentResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: UpdateAgentResponseResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "UpdateAgentResponseResponseBody";
        Object.setPrototypeOf(this, UpdateAgentResponseResponseBody.prototype);
    }
}

/**
 * Bad Request
 */
export class UpdateAgentResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error_message" })
    errorMessage?: string;

    constructor(err?: UpdateAgentResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "UpdateAgentResponseBody";
        Object.setPrototypeOf(this, UpdateAgentResponseBody.prototype);
    }
}
