/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export type Paginated<Result> = Result & { next: Paginator<Result> };
export type Paginator<Result> = () => Promise<Paginated<Result>> | null;
