/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../components";
import { AxiosResponse } from "axios";

export class GetAgentRequest extends SpeakeasyBase {
  /**
   * Unique id of the agent to be retrieved.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=agent_id",
  })
  agentId: string;
}

export class GetAgentResponse extends SpeakeasyBase {
  /**
   * Successfully retrieved an agent.
   */
  @SpeakeasyMetadata()
  agent?: components.Agent;

  /**
   * HTTP response content type for this operation
   */
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * HTTP response status code for this operation
   */
  @SpeakeasyMetadata()
  statusCode: number;

  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  @SpeakeasyMetadata()
  rawResponse: AxiosResponse;
}
