/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../components";
import { AxiosResponse } from "axios";

export class GetCallRequest extends SpeakeasyBase {
  /**
   * The call id to retrieve call history for.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=call_id",
  })
  callId: string;
}

export class GetCallResponse extends SpeakeasyBase {
  /**
   * Successfully retrieved an agent.
   */
  @SpeakeasyMetadata()
  callDetail?: components.CallDetail;

  /**
   * HTTP response content type for this operation
   */
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * HTTP response status code for this operation
   */
  @SpeakeasyMetadata()
  statusCode: number;

  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  @SpeakeasyMetadata()
  rawResponse: AxiosResponse;
}
