/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../components";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class UpdatePhoneAgentRequestBody extends SpeakeasyBase {
  /**
   * Unique agent id to associate with this phone number.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "agent_id" })
  agentId: string;
}

export class UpdatePhoneAgentRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: UpdatePhoneAgentRequestBody;

  /**
   * Phone number in E.164 format that require agent update.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=phone_number",
  })
  phoneNumber: string;
}

export class UpdatePhoneAgentResponse extends SpeakeasyBase {
  /**
   * HTTP response content type for this operation
   */
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Successfully updated the phone number's agent.
   */
  @SpeakeasyMetadata()
  phoneNumber?: components.PhoneNumber;

  /**
   * HTTP response status code for this operation
   */
  @SpeakeasyMetadata()
  statusCode: number;

  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  @SpeakeasyMetadata()
  rawResponse: AxiosResponse;
}
