/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type UpdateAgentRequestBody = {
  /**
   * The name of the agent. Only used for your own reference.
   */
  agentName?: string | undefined;
  /*
   * The URL we will establish LLM websocket for getting response, usually your server.
   */
  llmWebsocketUrl?: string | undefined;
  /**
   * Unique voice id used for the agent. Find list of available voices in documentation.
   */
  voiceId?: string | undefined;
  /**
   * Controls whether the agent would backchannel (agent interjects the speaker with phrases like "yeah", "uh-huh" to signify interest and engagement).
   */
  enableBackchannel?: boolean | undefined;
  /**
    * Controls how stable the voice is.
    */
  voiceTemperature?: number | undefined;
};

/** @internal */
export namespace UpdateAgentRequestBody$ {
  export type Inbound = {
    agent_name?: string | undefined;
    llm_websocket_url?: string | undefined;
    voice_id?: string | undefined;
    enable_backchannel?: boolean | undefined;
    voice_temperature?: number | undefined;
  };

  export const inboundSchema: z.ZodType<
    UpdateAgentRequestBody,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      agent_name: z.string().optional(),
      llm_websocket_url: z.string(),
      voice_id: z.string(),
      enable_backchannel: z.boolean().optional(),
      voice_temperature: z.number().optional()
    })
    .transform((v) => {
      return {
        ...(v.agent_name === undefined ? null : { agentName: v.agent_name }),
        ...(v.llm_websocket_url === undefined
          ? null
          : { llmWebsocketUrl: v.llm_websocket_url }),
        ...(v.voice_id === undefined ? null : { voiceId: v.voice_id }),
        ...(v.enable_backchannel === undefined ? null : { enableBackchannel: v.enable_backchannel }),
        ...(v.voice_temperature === undefined ? null : { voiceTemperature: v.voice_temperature }),
      };
    });

  export type Outbound = {
    agent_name?: string | undefined;
    llm_websocket_url?: string | undefined;
    voice_id?: string | undefined;
    enable_backchannel?: boolean | undefined;
    voice_temperature?: number | undefined;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    UpdateAgentRequestBody
  > = z
    .object({
      agentName: z.string().optional(),
      llmWebsocketUrl: z.string().optional(),
      voiceId: z.string().optional(),
      enableBackchannel: z.boolean().optional(),
      voiceTemperature: z.number().optional()
    })
    .transform((v) => {
      return {
        ...(v.agentName === undefined ? null : { agent_name: v.agentName }),
        ...(v.llmWebsocketUrl === undefined
          ? null
          : { llm_websocket_url: v.llmWebsocketUrl }),
        ...(v.voiceId === undefined ? null : { voice_id: v.voiceId }),
        ...(v.enableBackchannel === undefined ? null : { enable_backchannel: v.enableBackchannel }),
        ...(v.voiceTemperature === undefined ? null : { voice_temperature: v.voiceTemperature }),
      };
    });
}

export type UpdateAgentRequest = {
  requestBody: UpdateAgentRequestBody;
  /**
   * Unique id of the agent to be updated.
   */
  agentId: string;
};

export type UpdateAgentResponse = {
  /**
   * Successfully updated an agent.
   */
  agent?: components.Agent | undefined;
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export namespace UpdateAgentRequest$ {
  export type Inbound = {
    RequestBody: UpdateAgentRequestBody$.Inbound;
    agent_id: string;
  };

  export const inboundSchema: z.ZodType<
    UpdateAgentRequest,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      RequestBody: UpdateAgentRequestBody$.inboundSchema,
      agent_id: z.string(),
    })
    .transform((v) => {
      return {
        requestBody: v.RequestBody,
        agentId: v.agent_id,
      };
    });

  export type Outbound = {
    RequestBody: UpdateAgentRequestBody$.Outbound;
    agent_id: string;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    UpdateAgentRequest
  > = z
    .object({
      requestBody: UpdateAgentRequestBody$.outboundSchema,
      agentId: z.string(),
    })
    .transform((v) => {
      return {
        RequestBody: v.requestBody,
        agent_id: v.agentId,
      };
    });
}

/** @internal */
export namespace UpdateAgentResponse$ {
  export type Inbound = {
    Agent?: components.Agent$.Inbound | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: Response;
  };

  export const inboundSchema: z.ZodType<
    UpdateAgentResponse,
    z.ZodTypeDef,
    Inbound
  > = z
    .object({
      Agent: components.Agent$.inboundSchema.optional(),
      ContentType: z.string(),
      StatusCode: z.number().int(),
      RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
      return {
        ...(v.Agent === undefined ? null : { agent: v.Agent }),
        contentType: v.ContentType,
        statusCode: v.StatusCode,
        rawResponse: v.RawResponse,
      };
    });

  export type Outbound = {
    Agent?: components.Agent$.Outbound | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
  };

  export const outboundSchema: z.ZodType<
    Outbound,
    z.ZodTypeDef,
    UpdateAgentResponse
  > = z
    .object({
      agent: components.Agent$.outboundSchema.optional(),
      contentType: z.string(),
      statusCode: z.number().int(),
      rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
      }),
    })
    .transform((v) => {
      return {
        ...(v.agent === undefined ? null : { Agent: v.agent }),
        ContentType: v.contentType,
        StatusCode: v.statusCode,
        RawResponse: v.rawResponse,
      };
    });
}
