/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Phone number associated with the call. Only populated when call_type is `inbound_phone_call` or `outbound_phone_call`.
 */
export class CallPhoneNumber extends SpeakeasyBase {
    /**
     * Caller phone number in E.164 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "from" })
    from: string;

    /**
     * Callee phone number in E.164 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "to" })
    to: string;
}
